/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package co.unicauca.microkernel.client.presentation;

/**
 *
 * @author Usuario
 */
public class GUIAgregarComponentes extends javax.swing.JFrame {

    /** Creates new form GUIMenuClient */
    public GUIAgregarComponentes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_IdComp = new javax.swing.JLabel();
        lbl_TipoComp = new javax.swing.JLabel();
        lbl_NomComp = new javax.swing.JLabel();
        txt_nomComp = new javax.swing.JTextField();
        lbl_PrecioComp = new javax.swing.JLabel();
        txt_PriceComp = new javax.swing.JTextField();
        cbx_tipoComp = new javax.swing.JComboBox<>();
        txt_IdComp = new javax.swing.JTextField();
        btn_AgregarComp = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_CargarImagenComp = new javax.swing.JButton();
        lbl_ImageComp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Componente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 250, 30));

        lbl_IdComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_IdComp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IdComp.setText("ID:");
        getContentPane().add(lbl_IdComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 20, 40));

        lbl_TipoComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_TipoComp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TipoComp.setText("Tipo:");
        getContentPane().add(lbl_TipoComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        lbl_NomComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_NomComp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NomComp.setText("Nombre:");
        getContentPane().add(lbl_NomComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 50, 40));
        getContentPane().add(txt_nomComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 100, -1));

        lbl_PrecioComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_PrecioComp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PrecioComp.setText("Precio:");
        getContentPane().add(lbl_PrecioComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));
        getContentPane().add(txt_PriceComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, 20));

        cbx_tipoComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Principio", "Proteina", "Bebida" }));
        getContentPane().add(cbx_tipoComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));
        getContentPane().add(txt_IdComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, -1));

        btn_AgregarComp.setText("Agregar");
        getContentPane().add(btn_AgregarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        btn_salir.setText("Salir");
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        btn_CargarImagenComp.setText("Elegir Imagen");
        getContentPane().add(btn_CargarImagenComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lbl_ImageComp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        getContentPane().add(lbl_ImageComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/componentes.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgregarComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarComp;
    private javax.swing.JButton btn_CargarImagenComp;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbx_tipoComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_IdComp;
    private javax.swing.JLabel lbl_ImageComp;
    private javax.swing.JLabel lbl_NomComp;
    private javax.swing.JLabel lbl_PrecioComp;
    private javax.swing.JLabel lbl_TipoComp;
    private javax.swing.JTextField txt_IdComp;
    private javax.swing.JTextField txt_PriceComp;
    private javax.swing.JTextField txt_nomComp;
    // End of variables declaration//GEN-END:variables

}
