/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.common.entities.User;
import co.unicauca.microkernel.core.domain.UserRepository;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIMenuAdministrador extends JFrame {

    UserRepository service;
    /** Creates new form GUIRegistrarUsuario */
    public GUIMenuAdministrador() {
        initComponents();
        this.service = service;
        setLocationRelativeTo(null);
        setSize(510, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_MenuAdministrador = new javax.swing.JLabel();
        btn_editarMenuEspecial = new javax.swing.JButton();
        btn_AgregarComp = new javax.swing.JButton();
        btn_ListarComp = new javax.swing.JButton();
        btn_ListarPlatos = new javax.swing.JButton();
        btn_editarMenuDia = new javax.swing.JButton();
        btn_agregarPlato = new javax.swing.JButton();
        Btn_CerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MenuAdministrador.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lbl_MenuAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MenuAdministrador.setText("Menu Administrador");
        lbl_MenuAdministrador.setDoubleBuffered(true);
        getContentPane().add(lbl_MenuAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btn_editarMenuEspecial.setText("Menú Especial");
        getContentPane().add(btn_editarMenuEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, -1));

        btn_AgregarComp.setText("Agregar Componente");
        btn_AgregarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarCompActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AgregarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));

        btn_ListarComp.setText("Listar Componentes");
        getContentPane().add(btn_ListarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        btn_ListarPlatos.setText("Listar Platos Especiales");
        getContentPane().add(btn_ListarPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        btn_editarMenuDia.setText(" Menú del día");
        getContentPane().add(btn_editarMenuDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, -1));

        btn_agregarPlato.setText("Agregar Plato Especial");
        btn_agregarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPlatoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        Btn_CerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        Btn_CerrarSesion.setForeground(new java.awt.Color(0, 0, 153));
        Btn_CerrarSesion.setText("Cerrar Sesión");
        Btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarCompActionPerformed
       GUIAgregarComponentes guiComponent = new GUIAgregarComponentes (); 
       this.setVisible (false);        
       guiComponent.setVisible (true); 
       this.dispose();
    }//GEN-LAST:event_btn_AgregarCompActionPerformed

    private void Btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionActionPerformed
       GUISelectorTipoUser guiInicio = new GUISelectorTipoUser (); 
       this.setVisible (false);        
       guiInicio.setVisible (true); 
       this.dispose();
    }//GEN-LAST:event_Btn_CerrarSesionActionPerformed

    private void btn_agregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPlatoActionPerformed
       GUIAgregarPlatoEspecial guiDish = new GUIAgregarPlatoEspecial(); 
       this.setVisible (false);        
       guiDish.setVisible (true); 
       this.dispose();
    }//GEN-LAST:event_btn_agregarPlatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CerrarSesion;
    private javax.swing.JButton btn_AgregarComp;
    private javax.swing.JButton btn_ListarComp;
    private javax.swing.JButton btn_ListarPlatos;
    private javax.swing.JButton btn_agregarPlato;
    private javax.swing.JButton btn_editarMenuDia;
    private javax.swing.JButton btn_editarMenuEspecial;
    private javax.swing.JLabel lbl_MenuAdministrador;
    // End of variables declaration//GEN-END:variables

}
