package co.unicauca.microkernel.client.presentation;


import co.unicauca.microkernel.common.entities.Component;
import co.unicauca.microkernel.core.domain.ComponentRepository;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 * Interfaz gráfica de Consultar clientes
 *
 * @author Libardo Pantoja, Daniel Paz
 *
 */
public class GUIMenuDia extends javax.swing.JFrame {

    /**
     * Instancia de la gestion de componentes     
     */
     ComponentRepository service;

    /**
     * Constructor
     */
    public GUIMenuDia() {
        this.service = service;
        initComponents();
        setSize(870, 300);
        //loadDataTable();      
        setLocationRelativeTo(null);
    }

    
    /**
     * Carga los componentes en el jTable
     
    private void loadDataTable() {
      
        List<Component> components = service.findAllComponentes();
        DefaultTableModel modelTable = (DefaultTableModel) tblData.getModel();
        clearData(modelTable);
        for (Component component : components) {
            Object[] fila = new Object[3];
            fila[0] = component.getCompId();
            fila[1] = component.getCompName();
            fila[2] = component.getCompType();
            modelTable.addRow(fila);
        }
    }
     */
    /**
     * Elimina las filas del jTable
     *
     * @param modelTable modelo de datos del jTable
     */
    private void clearData(DefaultTableModel modelTable) {
        while (modelTable.getRowCount() > 0) {
            modelTable.removeRow(0);
        }
    }

    /**
     * Mensaje inicial del panel superior
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSur = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        pnlEste = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setTitle("Comidas del Menú Diario");

        pnlSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlSur.add(btnClose);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlEste.setBorder(new javax.swing.border.MatteBorder(null));
        pnlEste.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlEste, java.awt.BorderLayout.EAST);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    
    public static void main(String[] args) {
        GUIMenuDia gui = new GUIMenuDia();
        gui.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlEste;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

}
