/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package co.unicauca.microkernel.client.presentation;

import co.unicauca.microkernel.common.entities.User;
import co.unicauca.microkernel.core.domain.UserRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIRegistrarUsuario extends javax.swing.JFrame {

    UserRepository service;
    /** Creates new form GUIRegistrarUsuario */
    public GUIRegistrarUsuario() {
        initComponents();
        this.service = service;
        setLocationRelativeTo(null);
        setSize(510, 400);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblUserLastName = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserLoginName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserLastName = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        txtUserMobile = new javax.swing.JTextField();
        txtUserAddress = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btnRegistarUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Nombre(s):* ");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lblUserLastName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserLastName.setText("Apellido:*");
        getContentPane().add(lblUserLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblUserEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserEmail.setText("E-mail:*");
        getContentPane().add(lblUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Teléfono:* (+57)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Dirección:* ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Login:*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña:*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(txtUserLoginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 119, -1));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 119, -1));
        getContentPane().add(txtUserLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 119, -1));
        getContentPane().add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 119, -1));
        getContentPane().add(txtUserMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 119, -1));
        getContentPane().add(txtUserAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 119, -1));
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 119, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registro de Usuario");
        jLabel6.setDoubleBuffered(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnRegistarUsuario.setText("Registrarse");
        btnRegistarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/img_FondoRegistroUsuario.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarUsuarioActionPerformed
        co.unicauca.microkernel.common.entities.User  Usuario = new User(txtUserLoginName.getText(),txtUserPassword.getText(),txtUserName.getText(),txtUserLastName.getText(),txtUserAddress.getText(),txtUserMobile.getText(),txtUserEmail.getText());
        //Aqui vendria el analizar si el usuario existe en el sistema
        User varUser = service.invalidateUser(txtUserLoginName.getText());
        if (varUser!=null) {//El usuario fue encontrado
           JOptionPane.showMessageDialog(null, "El Login ya existe");
        } else {           
            String usuarioCreado=service.createUser(Usuario);
            JOptionPane.showMessageDialog(null, "Ha sido creado el usuario ", usuarioCreado, HEIGHT);//revisar
        }
    }//GEN-LAST:event_btnRegistarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserLastName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtUserAddress;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserLastName;
    private javax.swing.JTextField txtUserLoginName;
    private javax.swing.JTextField txtUserMobile;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables

}
